# Default values for envoy-ratelimit.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicaCount: 1

image:
  repository: rudydydy/ratelimit
  tag: latest
  pullPolicy: IfNotPresent

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP

resources: {}
  # We usually recommend not to specify default resources and to leave this as a conscious
  # choice for the user. This also increases chances charts run on environments with little
  # resources, such as Minikube. If you do want to specify resources, uncomment the following
  # lines, adjust them as necessary, and remove the curly braces after 'resources:'.
  # limits:
  #   cpu: 100m
  #   memory: 128Mi
  # requests:
  #   cpu: 100m
  #   memory: 128Mi

nodeSelector: {}

tolerations: []

affinity: {}

log_level: "debug"
use_statsd: "false"
runtime_root: "/"
runtime_subdirectory: "ratelimit/config"
redis:
  enabled: true
  socket_type: "tcp"
  # do fill below values if you plan to depend upon service like elacticache or memorystore
  external:
    host: ""
    port: "6379"
  usePassword: false

envoy:
  enabled: true

  service:
    enabled: true
    ## Service name is user-configurable for maximum service discovery flexibility.
    name: envoy
    type: LoadBalancer
    ports:
      n0:
        port: 80
        targetPort: n0
        protocol: TCP

  files:
    mekari.crt: |-
      qwerty

    envoy.yaml: |-
      ## refs:
      ## - https://www.envoyproxy.io/docs/envoy/latest/start/start#quick-start-to-run-simple-example
      ## - https://raw.githubusercontent.com/envoyproxy/envoy/master/configs/google_com_proxy.v2.yaml
      admin:
        access_log_path: /dev/stdout
        address:
          socket_address:
            address: 0.0.0.0
            port_value: 9901

      static_resources:
        listeners:
        - name: listener_0
          address:
            socket_address:
              address: 0.0.0.0
              port_value: 10000
          filter_chains:
          - filters:
            - name: envoy.http_connection_manager
              config:
                access_log:
                - name: envoy.file_access_log
                  config:
                    path: /dev/stdout
                stat_prefix: ingress_http
                codec_type: AUTO
                route_config:
                  name: local_route
                  virtual_hosts:
                  - name: local_service
                    domains: 
                    - "*"
                    rate_limits:
                    - stage: 0
                      actions:
                        - generic_key: 
                            descriptor_value: "global"
                    routes:
                    - match:
                        prefix: "/"
                      route:
                        host_rewrite: www.google.com
                        cluster: service_google
                http_filters:
                - name: envoy.rate_limit
                  config:
                    domain: apis
                    failure_mode_deny: true
                    rate_limit_service:
                      grpc_service:
                        envoy_grpc:
                          cluster_name: rate_limit_cluster
                        timeout: 0.25s

                - name: envoy.router

        clusters:
        - name: service_google
          connect_timeout: 2s
          type: LOGICAL_DNS
          dns_lookup_family: V4_ONLY
          lb_policy: ROUND_ROBIN
          hosts:
          - socket_google:
              address: google.com
              port_value: 443
          tls_context:
            sni: www.google.com

        - name: rate_limit_cluster
          type: strict_dns
          connect_timeout: 0.25s
          lb_policy: round_robin
          http2_protocol_options: {}
          hosts:
          - socket_address:
              address: ratelimit-envoy-ratelimit 
              port_value: 8081

files:
  config.yaml: |-
    domain: apis
    descriptors:
      - key: generic_key
        value: global
        rate_limit:
          unit: minute
          requests_per_unit: 10
