apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy-ratelimit.fullname" . }}
  labels:
    {{- include "envoy-ratelimit.labels" . | nindent 4 }}
data:
  USE_STATSD: {{ .Values.use_statsd | quote }}
  LOG_LEVEL: {{ .Values.log_level | quote }}
  REDIS_SOCKET_TYPE: {{ .Values.redis.socket_type | quote}}
  RUNTIME_ROOT: {{ .Values.runtime_root }}
  RUNTIME_SUBDIRECTORY: {{ .Values.runtime_subdirectory }}
{{- if .Values.redis.enabled }}
  REDIS_URL: "{{ .Release.Name }}-redis-master.{{ .Release.Namespace }}:6379"
{{- else }}
  REDIS_URL: "{{ .Values.redis.external.host }}:{{ .Values.redis.external.port }}"
{{- end }}
