apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "envoy-ratelimit.fullname" . }}-files
  labels:
    {{- include "envoy-ratelimit.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.files }}
  {{ $key }}: |-
{{ $value | default "" | indent 4 }}
{{- end -}}
