apiVersion: v1
kind: Service
metadata:
  name: {{ include "envoy-ratelimit.fullname" . }}
  labels:
    {{- include "envoy-ratelimit.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      protocol: TCP
      port: 8080
      targetPort: 8080
    - name: http2
      protocol: TCP
      port: 8081
      targetPort: 8081
    - name: server
      protocol: TCP
      port: 6070
      targetPort: 6070
  selector:
    {{- include "envoy-ratelimit.selectorLabels" . | nindent 4 }}
